version: "2"
run:
  timeout: 5m
  #tests: false
linters:
  default: all
  disable:
    - depguard
    - gomodguard
    - noctx
    - noinlineerr
    - nlreturn
    - paralleltest
    - testpackage
    - wsl
    - wsl_v5
  settings:
    errcheck:
      exclude-functions:
        - io.WriteString
        - (net/http.ResponseWriter).Write
    exhaustruct:
      allow-empty: true
      exclude:
        - net/http.Server
    goconst:
      ignore-string-values:
        - "default router"
    gosec:
      excludes:
        - G705
        - G706
    varnamelen:
      ignore-decls:
        - r *http.Request
        - w http.ResponseWriter
        - w *httptest.ResponseRecorder
  exclusions:
    generated: lax
    warn-unused: true
    presets:
    #  - comments
    #  - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - gofumpt
    - golines
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
