version: "2"
run:
  timeout: 5m
  tests: false
linters:
  default: all
  disable:
    - depguard
    - gochecknoglobals
    - noinlineerr
    - nlreturn
    - noctx
    - wsl
    - wsl_v5
  settings:
    exhaustruct:
      exclude:
        - net/http.Server
    varnamelen:
      ignore-decls:
        - w http.ResponseWriter
        - r *http.Request
    errcheck:
      exclude-functions:
        - io.WriteString
        - (net/http.ResponseWriter).Write
  exclusions:
    generated: lax
    warn-unused: true
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
